name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Show Files
        run: ls -la

      - name: Build Docker Image
        run: docker build -t github-actions-demo:v1 .

      - name: Run Docker Container
        run: docker run --rm github-actions-demo:v1
